### ISSUE TITLE
如何反代 Pixiv?

### ISSUE THREAD

**Issue by feilongproject** [rocket-booster/rocket-booster#38]
我想要反代pixiv，为了能够登入，我需要配置那些域名？
（可以的话能不能直接给个配置文件？）

**Comment by Berkeley-Reject** [comment]
需要建立多个 Workers, 为 `pixiv.net`, `pximg.net`, accounts.pixiv.net` 分别设置反代, 配置比较复杂.
如果只是想反代图片的话, 可以使用以下代码:
```javascript
addEventListener("fetch", event => {
  let url = new URL(event.request.url);
  url.hostname = "i.pximg.net";

  let request = new Request(url, event.request);
  event.respondWith(
    fetch(request, {
      headers: {
        'Referer': 'https://www.pixiv.net/',
        'User-Agent': 'Cloudflare Workers'
      }
    })
  );
});
```

**Comment by feilongproject** [comment]
> 需要建立多个 Worker, 为 `pixiv.net`, `pximg.net`, `accounts.pixiv.net` 分别设置反代, 配置比较复杂.
> 如果只是想反代图片的话, 可以使用以下代码:
> 
> ```js
> addEventListener("fetch", event => {
>   let url = new URL(event.request.url);
>   url.hostname = "i.pximg.net";
> 
>   let request = new Request(url, event.request);
>   event.respondWith(
>     fetch(request, {
>       headers: {
>         'Referer': 'https://www.pixiv.net/',
>         'User-Agent': 'Cloudflare Workers'
>       }
>     })
>   );
> });
> ```

问一下大佬可以能给个代理全站的demo么？如果可以的话不胜感激:）

**Comment by Berkeley-Reject** [comment]
> > 需要建立多个 Worker, 为 `pixiv.net`, `pximg.net`, `accounts.pixiv.net` 分别设置反代, 配置比较复杂.
> > 如果只是想反代图片的话, 可以使用以下代码:
> > ```js
> > addEventListener("fetch", event => {
> >   let url = new URL(event.request.url);
> >   url.hostname = "i.pximg.net";
> > 
> >   let request = new Request(url, event.request);
> >   event.respondWith(
> >     fetch(request, {
> >       headers: {
> >         'Referer': 'https://www.pixiv.net/',
> >         'User-Agent': 'Cloudflare Workers'
> >       }
> >     })
> >   );
> > });
> > ```
> 
> 问一下大佬可以能给个代理全站的demo么？如果可以的话不胜感激:）

明天做一下试试.

**Comment by Baizhixi** [comment]
Pixiv我记得有引用reCAPTCHA，所以也不能正常登陆

**Comment by Baizhixi** [comment]
> > > 需要建立多个 Worker, 为 `pixiv.net`, `pximg.net`, `accounts.pixiv.net` 分别设置反代, 配置比较复杂.
> > > 如果只是想反代图片的话, 可以使用以下代码:
> > > ```js
> > > addEventListener("fetch", event => {
> > >   let url = new URL(event.request.url);
> > >   url.hostname = "i.pximg.net";
> > > 
> > >   let request = new Request(url, event.request);
> > >   event.respondWith(
> > >     fetch(request, {
> > >       headers: {
> > >         'Referer': 'https://www.pixiv.net/',
> > >         'User-Agent': 'Cloudflare Workers'
> > >       }
> > >     })
> > >   );
> > > });
> > > ```
> > 
> > 
> > 问一下大佬可以能给个代理全站的demo么？如果可以的话不胜感激:）
> 
> 明天做一下试试.

请问一下最新进展怎么样了？
顺便可以参考这个
https://moe.best/technology/pixiv-proxy.html

**Comment by Baizhixi** [comment]
我试着搞了一下
https://www.pixivcn.site/
但是很奇怪的问题：
电脑端是能浏览不能搜索，搜索内容空白（控制台无报错，不知道原因）
移动端是首页图片403（不知道为什么没有替换url），搜索反而正常
